# Generated by Django 4.2 on 2025-02-08 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_artista', models.CharField(max_length=150)),
                ('pais_de_origen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Álbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_del_album', models.CharField(max_length=150)),
                ('anio_de_lanzamiento', models.DateField()),
                ('genero', models.CharField(choices=[('ELE', 'Electrónica'), ('MET', 'Metal'), ('POP', 'Pop'), ('JAZ', 'Jazz'), ('REG', 'Reggae'), ('LAT', 'Latina'), ('MER', 'Merengue'), ('PUN', 'Punk'), ('R&R', 'Rock & Roll'), ('DIS', 'Disco'), ('HIP', 'Hip-Hop'), ('Blu', 'Blues'), ('FUNK', 'Funk'), ('CUM', 'Cumbia'), ('BAl', 'Baladas'), ('FOL', 'Folk'), ('CRY', 'Country'), ('CLA', 'Clásica'), ('SAL', 'Salsa'), ('RAP', 'Rap')], max_length=150)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='p_images')),
                ('artista_asociado', models.ForeignKey(db_column='id_artista', on_delete=django.db.models.deletion.CASCADE, to='album_manager.artista')),
            ],
        ),
    ]
